"""create resources table

Revision ID: 76f07d6dccc6
Revises: 
Create Date: 2026-09-18 12:30:38.101940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '76f07d6dccc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('hospital', 'clinic', 'police', 'fire_service', 'shelter', 'emergency_office', 'ambulance', 'idp_camp', 'rescue_centre', 'other', name='resourcecategory'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.Enum('verified', 'unverified', 'needs_update', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_name'))
        batch_op.drop_index(batch_op.f('ix_resources_category'))

    op.drop_table('resources')
    # ### end Alembic commands ###
